language: ruby

services:
  - rabbitmq
  - redis
  - mongodb

matrix:
  include:
    - { rvm: ree,   gemfile: gemfiles/Gemfile_r3, env: SLEEP_FACTOR=10 }
    - { rvm: 1.9.3, gemfile: gemfiles/Gemfile_r3, env: SLEEP_FACTOR=10 }
    - { rvm: 2.0.0, gemfile: gemfiles/Gemfile_r3, env: SLEEP_FACTOR=10 }
    - { rvm: 2.0.0, gemfile: gemfiles/Gemfile_r4, env: SLEEP_FACTOR=10 }
  allow_failures:
    - { rvm: 2.0.0, gemfile: gemfiles/Gemfile_r3 }
    - { rvm: 2.0.0, gemfile: gemfiles/Gemfile_r4 }
